name: Setup Lefthook
author: Alfi Maulana
description: Set up Lefthook on the runner
branding:
  icon: anchor
  color: red
inputs:
  version:
    description: The version of Lefthook to install. Defaults to the latest version.
outputs:
  version:
    description: The version of Lefthook that was installed.
runs:
  using: node24
  main: dist/main.js
